SELECT  u.USER_ID, 
        NICKNAME, 
        CONCAT(CITY,SPACE(1), u.STREET_ADDRESS1,SPACE(1), u.STREET_ADDRESS2) AS "전체주소",  
        CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS "전화번호"
FROM USED_GOODS_BOARD b INNER JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY USER_ID DESC