SELECT  
    YEAR(o.SALES_DATE) YEAR,
    MONTH(o.SALES_DATE) MONTH,
    GENDER,
    COUNT(DISTINCT u.USER_ID) AS USERS
FROM USER_INFO u
JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
GROUP BY YEAR, GENDER, MONTH
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER