SELECT f.PRODUCT_ID, f.PRODUCT_NAME, SUM(o.AMOUNT*f.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT f INNER JOIN FOOD_ORDER o ON f.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY f.PRODUCT_ID, f.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, f.PRODUCT_ID ASC;