SELECT 
    CATEGORY, 
    SUM(s.SALES) AS TOTAL_SALES
FROM 
    BOOK b
INNER JOIN 
    BOOK_SALES s 
    ON b.BOOK_ID = s.BOOK_ID
WHERE 
    s.sales_date BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY 
    CATEGORY
ORDER BY 
    CATEGORY ASC;